devicetree-org/dt-schema

tools/dt-validate
When we have a disabled nodes, we don't want to validate that all the
required properties are there, since some might be external resources
usually provided by a DTS.
However, boards DTS that don't enable that component will not be able to
provide that resource and would fail to pass the required properties check.
We'll still want to validate the existing properties though.
In order to work around it, let's just ignore any error message mentionning
a missing required property on a disabled node.
=> dtschema: Deal with the disabled nodes

dtschema/lib.py
allOf is not the only keyword that can hold a subschema under it, but oneOf
and anyOf are also in that case. Let's make sure it's properly dealt with.
=> dtschema: Also expand conditionals under anyOf and oneOf

schemas/chosen.yaml, schemas/clock/clock.yaml
YAML escapes single quotes in a block of text using a backslash. Make sure
that it's there when we need it.
=> tree: Escape single quotes

meta-schemas/string-array.yaml
While one can specify a property as an enum, a const or a pattern, the
array meta-schemas only allows for enums or const. Let's add the patterns
as well.
=> meta-schemas: string-array: Pattern is a valid string description

schemas/clock/clock.yaml, schemas/dt-core.yaml, schemas/gpio/gpio.yaml, schemas/hwlock/hwlock-consumer.yaml, schemas/interrupts.yaml, schemas/mbox/mbox-consumer.yaml, schemas/phy/phy-consumer.yaml, schemas/power-domain/power-domain-consumer.yaml, schemas/pwm/pwm-consumer.yaml, schemas/reset/reset.yaml, schemas/types.yaml
So far, the string-array type mandates that all the items are not unique,
and this is enforced by default on all properties ending with the suffix
names.
However, a good number of the properties ending with names allow for
non-unique properties (gpio-line-names, pinctrl-names, dma-names, etc), and
this is pretty difficult to disable the unique check, which basically
requires to redefine the type all over again.
In order to ease the definitions of these properties, let's turn the logic
around. Instead, make string-array allow non-unique items, and let the
properties that don't allow it make it explicitly, which can be done pretty
easily with an allOf.
=> schemas: Revert the uniqueItems logic

schemas/chosen.yaml
simple-framebuffer has a reg property that needs to be translated to the
CPU addresses in order for that CPU to access the backing buffer, even
though the mapping in usually pretty trivial.
The devicetree specification says that a missing ranges property means that
we are crossing a non-translatable boundary, and therefore we wouldn't be
able to convert that address to a CPU address.
We thus need to allow ranges to be set on chosen.
=> schemas: chosen: Allow ranges to be specified

schemas/property-units.yaml
Some properties are using values in picoseconds, but unlike the micro,
milli and nano-seconds variants, the picoseconds prefix wasn't added.
Let's add it.
=> schemas: Validate the .*-ps properties

meta-schemas/cell.yaml, meta-schemas/core.yaml
The draft-8 will introduce the deprecated properties, and we want to start
using it to describe deprecation today.
Let's add it to the set of allowed properties.
=> meta-schemas: Allow the deprecated properties

meta-schemas/gpios.yaml
Some bindings will have some .*-gpio properties that we will want to
deprecate, but we want to still allow it bindings.
=> meta-schemas: gpios: Allow *-gpio properties

dtschema/lib.py
Even though it's pretty uncommon, select can have an arbitrary schema
underneath it.
In the case where it doesn't exists, our tools will generate an already
correct schema that doesn't need any fixup.
However, when one writes it by hand, that schemas isn't fixed up, and this
creates an odd situation where the schema under select doesn't really have
the same syntax than the rest of the schemas.
In order to address this, make sure we run the fixups on the schemas under
select if they exists.
=> dtschema: Fixup the schema under select

dtschema/lib.py
The current code adds a default $nodename property if it's not found in the
processed schema, and then calls the fixup functions.
Amongst those functions, add_select_schema will test whether $nodename is
found. If it is, then it will generate a select statement based on the
$nodename value, and if not, will generate a select statement set to false.
However, since we added the default before calling add_select_schema, that
latter condition never occurs, which can lead to schemas without a
compatible, $nodename or an explicit select statement being always selected
instead of never.
Such a case can happen with the recently merged in Linux 5.3 panel-common
schema.
Since no code seem to actually benefit from the default, let's remove the
default entirely.
Signed-off-by: Maxime Ripard …
=> dtschema: Remove $nodename default

meta-schemas/base.yaml, meta-schemas/cell.yaml
Those two comments are meant to allow some properties to be used in the schemas.
=> New properties

meta-schemas/core.yaml
The unevaluatedProperties was only allowed at the top-level of the schemas
so far, let's allow it for sub-schemas as well.
Signed-off-by: Maxime Ripard <mripard@kernel.org>
=> meta-schemas: core: Allow unevaluatedProperties in sub-schemas

schemas/chosen.yaml
This is based on kernel patch "fdt: add support for rng-seed".
Signed-off-by: Hsin-Yi Wang <hsinyi@chromium.org>
=> schemas: add rng-seed node schema

meta-schemas/clocks.yaml
Even though this is less ideal, "clocks" is both used as a generic
property name in many nodes, but also as a node name (mostly to group
multiple clocks as child nodes).
In the generic clock binding we acknowledge this and allow "clocks" to
be of type "object" as well, but fail to do so in the meta-schemas.
Add type object as an alternative to the phandles array to let DTs using
"clocks" as a node name pass the tests.
Signed-off-by: Andre Przywara <andre.przywara@arm.com>
=> clocks: Allow nodes being called "clocks"

README.md, schemas/gpio/gpio-consumer.yaml, schemas/gpio/gpio-hog.yaml, schemas/gpio/gpio.yaml, schemas/pci/pci-bus.yaml
These changes contain a few typofixes for the README. A new schema is added for GPIO hogs in a way that they don't conflict with the GPIO consumer bindings. Finally the PCI bus schema is modified to support an empty 'ranges' property, which is useful for PCI root ports which don't need any extra translation on top of the PCI host bridge translation.
=> PCI and GPIO updates, typofixes

meta-schemas/keywords.yaml
According to the json-schema specification, additionalProperties and
unevaluatedProperties must be a valid JSON schema and it doesn't put
any further restrictions on them.
Match the specification by allowing both to be either boolean or a
sub-schema.
Signed-off-by: Thierry Reding <treding@nvidia.com>
=> meta-schemas: Allow *Properties to be any schema

tools/dt-validate
When deciding whether or not to emit an error, look at the 'status'
property of the instance that failed to validate rather than of the
node that is being checked.
Cases where this can happen are when a schema describes required
properties for patternProperties or other child nodes, in which case
the invalid instance differs from the node being checked.
Signed-off-by: Thierry Reding <treding@nvidia.com>
=> dt-validate: Check status of correct instance

meta-schemas/core.yaml
The 'memory-region-names' property can be used to distinguish between
multiple entries in the 'memory-region' property. Document the new
property and model the dependency in the same way as for the 'clocks'
and 'clock-names' properties.
Signed-off-by: Thierry Reding <treding@nvidia.com>
=> meta-schemas: Document 'memory-region-names' property

schemas/simple-bus.yaml
This property indicates that nodes which are direct children of this bus
shall use non-posted (i.e. no early return) MMIO mapping modes when
mapping MMIO registers. This is a requirement that can be imposed by the
bus on otherwise generic devices.
Also included a drive-by fix for the description, which was incorrect.
Signed-off-by: Hector Martin <marcan@marcan.st>
=> simple-bus: Add nonposted-mmio property

schemas/dt-core.yaml
As per Devicetree Specification, Release v0.3, status can have "okay",
"disabled", "reserved", "fail", "fail-sss" as valid values.
While "fail" and "fail-sss" descriptions could indicate a variable
and potentially dynamic definition, "reserved" is more clear and static
description. Lets add that to the enum list.
Signed-off-by: Nishanth Menon <nm@ti.com>
=> schemas/dt-core: Add "reserved" as valid value for status property

schemas/root-node.yaml
This patch adds an optional 'chassis-type' property to the root node in order to specify the device form factor, mimicking what is already available through DMI on ACPI-based systems.
Such information can be useful (for example, in order to implement different behavior on a desktop and on a smartphone) but is not currently available on DT-based systems.
Possible values are identical to those used by systemd's [hostnamed](https://www.freedesktop.org/software/systemd/man/machine-info.html#CHASSIS=).
Related specification proposal: https://github.com/devicetree-org/devicetree-specification/pull/45
=> schemas: root-node: Introduce 'chassis-type' property

schemas/cpus.yaml
As discussed in [1] and [2], CPU nodes have an unusual interpretation of
the "disabled" status. Explicitly document the okay, disabled and fail
status values in cpus.yaml.
[1] https://www.lkml.org/lkml/2020/8/26/1237
[2] https://www.spinics.net/lists/devicetree-spec/msg01007.html
Signed-off-by: Matthias Schiffer <matthias.schiffer@ew.tq-group.com>
I wasn't able to actually verify anything against this schema. It seems that the "status" property has some special behaviour that makes unknown values pass validation?
=> schemas: cpus: document CPU-specific "status" property

schemas/dt-core.yaml
Support a 'label' property on all device nodes.
This property is useful to be able to identify an individual device when multiple individual ones are present in the system.
Note that this is already supported (but not documented) by the IIO subsystem on Linux.
I wonder if this property should be usable everywhere by default, without requiring the specific device shemas to add `label: true`?
=> schemas: core: Add 'label' property

schemas/pci/pci-bus.yaml, schemas/property-units.yaml
Add 'slot-power-limit-milliwatt' property that specifies slot power
limit, which is a form-factor and board specific value and must be
initialized by hardware.
Some PCIe controllers delegate this work to software to allow hardware
flexibility and therefore this property basically specifies what should
host bridge program into PCIe Slot Capabilities registers.
The property needs to be specified in milliwatts unit instead of the
special format defined by Slot Capabilities register (which encodes
scaling factor or different unit). Host drivers should convert the value
from milliwatts to the needed format.
Signed-off-by: Pali Rohár <pali@kernel.org>
Signed-off-by: Marek Behún <marek.behun@nic.cz>
=> schemas: pci-bus: Add 'slot-power-limit-milliwatt' property

dtschema/schemas/i2c/i2c-controller.yaml
In some cases, operating systems may attempt to detect the presence of
devices on an I2C bus by, for example, attempting to read specific
registers from a list of addresses which some common peripherals is
known to use.
Add a property which can be used to indicate that there are no devices
on the bus except the ones listed in the devicetree, thus allowing
operating systems to choose to avoid spending time on attempting this
kind of detection of devices which do not exist.
Signed-off-by: Vincent Whitchurch <vincent.whitchurch@axis.com>
=> schemas: i2c-controller: Add 'no-detect' property

dtschema/schemas/chosen.yaml
Add string property allowing to pass down the name of the selected
image configuration node of a uImage.FIT to the operating system.
Signed-off-by: Daniel Golle <daniel@makrotopia.org>
Suggested and discussed also on the U-Boot Mailing List <u-boot@lists.denx.de>
https://patchwork.ozlabs.org/project/uboot/patch/YjkIr8wmz1XEOVNh@makrotopia.org/
If this generally sounds acceptable, I will send a v2 to the U-Boot Mailing List with the property now being called `u-boot,bootconf` as suggested here (originally I simply named it `bootconf`)
=> schemas: chosen: Add 'u-boot,bootconf' node

dtschema/schemas/chosen.yaml
Add a string property to pass down the U-Boot version to the operating
system.
Related change in U-Boot: https://lore.kernel.org/all/20220519142226.121348-1-francesco.dolcini@toradex.com/
=> schemas: chosen: Add 'u-boot,version' property

dtschema/schemas/i2c/i2c-controller.yaml
These tabs prevent YAML from being loaded inside a python script with 
PyYAML.
Error "yaml.scanner.ScannerError: while scanning for the next token 
found character '\t' that cannot start any token"
=> schemas: i2c: Remove tabs from line 168

dtschema/schemas/dt-core.yaml
When using dma-coherent, the assumption is that the system is noncoherent
in general with specific devices being coherent.
Similarly there can be systems being coherent by default with specific
devices being noncoherent.
Add a 'dma-noncoherent' property to the schema which also got added to
the specification.
Signed-off-by: Heiko Stuebner <heiko@sntech.de>
=> schemas: add dma-noncoherent property

tools/dt-validate
Validation of a node with with disabled nodes is failing, if the schema references multiple other schemas in oneOf.  For example:
```
mdss {
...
dsi-phy@... {
...
// Some required property is missing
status = "disabled";
};
};
```
and schema:
```
properties:
"^dsi-phy@[1-9a-f][0-9a-f]*$":
type: object
oneOf:
- $ref: dsi-phy-14nm.yaml
- $ref: dsi-phy-20nm.yaml
- $ref: dsi-phy-28nm.yaml
```
The check_node() was ignoring errors for disabled nodes if they contained 'required property' in error message or all of sub-errors do not have such error.  Thus if any of referenced schemas failed with any other error, the entire check failed.
Rework check_node() so it will ignore errors for disabled nodes if any of messages contain 'required property'.
This might hide some useful errors, but only for …
=> dt-validate: if node is disabled, pass on any missing property

dtschema/schemas/phy/phy-provider.yaml
With the (pending) [addition of PHY_TYPE_2500BASEX and PHY_TYPE_10GBASER](https://lore.kernel.org/linux-phy/20220902213721.946138-2-sean.anderson@seco.com/), the maximum value for `phy-type` must also be increased.
=> schemas: phy: Increase phy-type maximum

dtschema/schemas/phy/phy-provider.yaml
With the combination of [PHY_TYPE_USXGMII](https://lore.kernel.org/r/20220628122255.24265-3-rogerq@kernel.org) and (soon to be resent) [PHY_TYPE_2500BASEX and PHY_TYPE_10GBASER](https://lore.kernel.org/linux-phy/20220902213721.946138-2-sean.anderson@seco.com/), the maximum value for phy-type must be increased to 14.
=> schemas: phy: Once again increase phy-type maximum

dtschema/schemas/phy/phy-provider.yaml
Several Devicetree nodes in Linux kernel are named "phy", but they do not have "#phy-cells" property.  Instead their children have it.  This leads to a lot of false positives, so relax the requirement and do not enforce having #phy-cells for every "phy" node.
Fixes: #22 
Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
=> schemas: relax phy-cells requirement for PHY-like nodes

dtschema/meta-schemas/cell.yaml
YAML syntax treats # sign with leading space as a comment. Fix it by placing quotation mark around it.
Signed-off-by: Michał Grzelak <mchl.grzlk@gmail.com>
=> meta-schemas: cell: Add quotation marks

dtschema/schemas/opp/opp.yaml
Several devices use Operating Performance Points and are consumers of the Performance or Power Domain controllers.  Document common 'operating-points-v2' and 'required-opps' properties.
Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
=> schemas: add basic OPP consumer bindings

dtschema/schemas/i2c/i2c-controller.yaml
The I2C specification allows for the clock line to be held low for a specified timeout to force the slave device into a 'wait' mode. This feature is known as 'Clock stretching' and is optional.
In the NXP I2C specification, clock stretching is described as the process of pausing a transaction by holding the SCL line LOW. The transaction can only continue when the line is released HIGH again.[*] However, most target devices do not include an SCL driver and are therefore unable to stretch the clock.
Add the following properties:
- i2c-scl-clk-low-timeout-us: This property specifies the duration, in microseconds, for which the clock is kept low and a client needs to detect a forced waiting state.
- i2c-scl-has-clk-low-timeout: This property specifies whether the I2C controller implements the …
=> schemas: i2c: Add the clock stretching property

dtschema/schemas/property-units.yaml
Some hardware has negative percentage adjustments. Allow it.
=> schemas: property-units: Allow negative values for % units

dtschema/schemas/options/u-boot.yaml
Add bootscr-address and offset-from-ram-start properties to help in easier picking of boot script file when automated flows are used.
The bootscr-address holds the full 64 bit address of the bootscript file.
The bootscr-offset-from-ram-start holds the offset address of the bootscript file from the start of the ram base in systems with RAM detection.
=> dt-bindings: u-boot: Add variables for bootscript location

dtschema/meta-schemas/keywords.yaml, dtschema/schemas/dt-core.yaml
Commit 0e28a44059a6 ("meta-schemas: Allow '#' anywhere is DT property names") amended the `propertyNames` regex to allow names such as `marvell,#interrupts`.
Make the same amendment to the `required` regex for consistency to avoid errors like:
```
Documentation/devicetree/bindings/security/tpm/ibm,vtpm.yaml: required:4: 'ibm,#dma-address-cells' does not match '^([a-zA-Z#][a-zA-Z0-9,+\\-._@]{0,63}|\\$nodename)$'
hint: 'required' must be valid DT property or node names
from schema $id: http://devicetree.org/meta-schemas/keywords.yaml#
```
=> meta-schemas: Allow '#' anywhere in required DT property names

dtschema/schemas/thermal/thermal.yaml
This adds a schema for thermal-zones consumers, useful for smart voltage scaling drivers that need to adjust CPU/GPU/other voltages based on chip quality and temperature of one or multiple zones, and for battery charge drivers that need to scale the charging current based on board dependant thermal zones readings (for example, battery temperature, device skin temperature, etc).
For more information, please look at https://lore.kernel.org/all/20231115144857.424005-1-angelogioacchino.delregno@collabora.com/
Cheers!
Angelo
=> schemas: Add a schema for thermal consumer

dtschema/dtb.py
The 'nvmem-cells' has corresponding '#nvmem-cell-cells' property defining number cells, thus allow checks for phandle arguments.
Link: https://lore.kernel.org/linux-devicetree/20240109213739.558287-1-krzysztof.kozlowski@linaro.org/T/#u
Link: https://github.com/devicetree-org/dt-schema/pull/89
=> dtb: expect nvmem-cell-cells

dtschema/schemas/iio/iio-consumer.yaml, dtschema/schemas/iio/iio.yaml
IIO backends are devices connected to another IIO devices (consumers of the backends) providing services so that the consumer IIO device can be fully functional. One typical example of such an Hardware arrangement would be an high speed ADC that is connected to an FPGA IP core (through a serial data interface as LVDS) capable of handling the high sample rates. Examples of the provided services would be channel enablement/disablement.
While at it, fixed a typo in the top level description 'thes -> they'.
---
For more information, there's the current linux [patchseries](https://lore.kernel.org/linux-iio/20231208-dev-iio-backend-v2-0-5450951895e1@analog.com/) adding support for iio backends.
=> schemas: iio: iio-consumer: add io-backends schema

dtschema/extract_example.py, dtschema/validator.py
This commit fixes the following warnings:
extract_example.py: SyntaxWarning: invalid escape sequence '\s'
root_node = re.search('/\s*{', ex)
extract_example.py: SyntaxWarning: invalid escape sequence '\s'
int_val = re.search('\sinterrupts\s*=\s*<([0-9a-zA-Z |()_]+)>', ex).group(1)
validator.py: SyntaxWarning: invalid escape sequence '\-'
del props['^[a-z][a-z0-9\-]*$']
validator.py: SyntaxWarning: invalid escape sequence '\^'
prog = re.compile('.*[\^\[{\(\$].*')
validator.py: SyntaxWarning: invalid escape sequence '\-'
if c != '^[a-zA-Z0-9][a-zA-Z0-9,+\-._/]+$':
=> Fix SyntaxWarning: invalid escape sequence

dtschema/schemas/pci/pci-pci-bridge.yaml
There is no standard way to detect the D3 support of the PCI-PCI bridges. So let's add a new property, "supports-d3" to specify that the bridge supports transitioning to D3 states.
=> schemas: pci: bridge: Document "supports-d3" property

dtschema/schemas/chosen.yaml
These properties were moved from 64-bit-specific schemas, but were never updated to allow non-64-bit memory ranges. Since there is nothing 64-bit-specific about them, update their definitions to allow 32-bit memory ranges.
=> schemas: chosen: Allow 32-bit memory ranges for memory range properties

README.md
The link to the documentation is not valid anymore. There are at least two sections that might be used as a replacement ("Specification" and "Getting Started"), but to avoid a broken link in the future, point to the main site.
=> README: fix broken link to json-schema.org

dtschema/schemas/chosen.yaml
The property linux,tpm-kexec-buffer has not been implemented by Linux and therefore needs to be removed.
=> schemas: chosen: Remove 'linux,tpm-kexec-buffer'

dtschema/schemas/pci/pci-pci-bridge.yaml
Device schemas referencing pci-pci-bridge.yaml might have additional properties.
=> schemas: pci: allow additional device properties in pci-pci-bridge

dtschema/fixups.py, dtschema/meta-schemas/clocks.yaml, dtschema/schemas/clock/clock.yaml
To support rates that exceeds UINT32_MAX, introduce assigned-clock-rates-u64
=> schemas: introduce assigned-clock-rates-u64

dtschema/schemas/dt-core.yaml
Some components can not be absolutely determined to exist on a given device when the device tree is written or compiled. However such components can either be probed using I2C transfers, or determined to exist based on runtime information, such as GPIO or ADC strappings, or extra information passed over from boot firmware or read from some flash chip.
Such an arrangement of components are commonly seen in the consumer electronics world, where the manufacturer will swap out electrically compatible components due to inventory or price constraints. These components are commonly attached to the baseboard with a standardized ribbon cable, and the ribbon cable may contain strapping resistors if necessary.
Introduce a new "fail-needs-probe" status string that corresponds to devices or components …
=> schemas: core: Introduce "fail-needs-probe" status

dtschema/schemas/root-node.yaml
The 'television' chassis-type includes Smart TVs and set-top boxes, or any remote-controlled displays in general.
---
Hi,
I plan to use this chassis type in version 2 of the patches to add [initial device trees for Apple A7-A11 SoC based devices](https://lore.kernel.org/asahi/20240911084353.28888-2-towinchenmi@gmail.com/),
which includes Apple TV.
Relevant documentation PR: https://github.com/devicetree-org/devicetree-specification/pull/79
Nick Chan
=> schemas: root-node: Add 'television' chassis-type

dtschema/schemas/gpio/gpio-nexus-node.yaml, dtschema/schemas/gpio/gpio.yaml
[Nexus nodes](https://devicetree-specification.readthedocs.io/en/v0.3/devicetree-basics.html#nexus-nodes-and-specifier-mapping) were introduced with devicetree specification 0.3 and allow routing gpios, clock, etc to different controllers, etc.
Here I am trying to introduce GPIO nexus node binding since I am not sure how dependence for a general nexus node might be written.
I am also removing `#gpio-cells` dependence on `gpio-controller` since nexus node is not a controller.
=> Add schema for GPIO nexus nodes

dtschema/validator.py
This can apparently fall off the bike:
SCHEMA  Documentation/devicetree/bindings/processed-schema.json Traceback (most recent call last):
File "/home/konrad/.local/bin/dt-mk-schema", line 38, in <module>
schemas = dtschema.DTValidator(args.schemas).schemas
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/dtschema/validator.py", line 373, in __init__
self.make_property_type_cache()
File "/usr/lib/python3.12/site-packages/dtschema/validator.py", line 460, in make_property_type_cache
self.props, self.pat_props = get_prop_types(self.schemas)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/dtschema/validator.py", line 195, in get_prop_types
del props[r'^[a-z][a-z0-9\-]*$']
~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '^[a-z][a-z0-9\\-]*$'
make[2]: *** …
=> validator: Don't crash if the de-aliaser hack fails

dtschema/schemas/options/u-boot.yaml
Add property for LED boot and activity and period for blink mode.
These property define the LED label to use for the u-boot boot or activity LED to signal successful boot or activity like flash write or tftp traffic.
=> dt-bindings: u-boot: Add property for LED boot and activity

dtschema/schemas/pci/pci-bus-common.yaml
PCIe equalization presets are predefined settings used to optimize signal integrity by compensating for signal loss and distortion in high-speed data transmission.
As per PCIe spec 6.0.1 revision section 8.3.3.3 & 4.2.4 for data rates of  8.0 GT/s, 16.0 GT/s, 32.0 GT/s and 64.0 GT/s provides a way to configure lane equalization presets for each lane to enhance the PCIe link reliability. Each preset value represents a different combination of pre-shoot and de-emphasis values.
For each data rate it may be required to have a different preset configuration and each lane will have different preset values.
Define per data rate equalization preset property with array of 16 representing 16 lanes of the PCIe.
=> schemas: pci: bridge: Document PCIe equalization presets

dtschema/schemas/trigger/trigger-source.yaml
Add a new binding for trigger source providers and consumers. This is essentially the trigger source bindings from the leds subsystem in the Linux kernel, but with more generic descriptions and no restrictions on #trigger-source-cells.
As requested in https://lore.kernel.org/linux-spi/20241119164429.GB1769375-robh@kernel.org/
=> dt-bindings: trigger: Add trigger source

dtschema/schemas/access-controller/access-controller-consumer.yaml
Add a new binding access controller consumers. There are bus resource domain controllers, eFuse access controllers, so add the consumer bindings for various nodes to use.
=> schemas: Add access controller consumer

dtschema/schemas/property-units.yaml
Add the picoamp type.
This will be required for a new revision of a dt-bindings patch for. Series here:
[https://lore.kernel.org/r/20250106-apds9160-driver-v4-0-f88d9fc45d84@dimonoff.com](url)
Relevant comment regarding this change here:
[https://lore.kernel.org/all/20250118114846.78ce0b67@jic23-huawei/](url)
=> schemas: property-units: Add the picoamp type

dtschema/schemas/gpio/gpio-hog.yaml
Bring some sort of uniformity by allowing only "-hog" suffix, not prefix, for gpio-hog node names.
There is only one user of dropped prefix pattern in the Linux kernel DTS, being fixed in patch:
https://lore.kernel.org/linux-devicetree/20250115204603.136997-1-krzysztof.kozlowski@linaro.org/
=> schemas: gpio: Restrict HOG node name pattern to suffixes

dtschema/schemas/root-node.yaml
With the growing interest in the AR/VR/XR devices, it is expected that more and more devices will have the spectacles or eyeglasses-like form factor. Follow the devicetree specification change and add 'spectacles' as to list of possible values for the 'chassis-type' property.
=> schemas: root-node: add 'spectacles' chassis-type

dtschema/schemas/reg.yaml
In some rather bizarre cases, a different kind of memory mapping may be necessary for only some specific devices, with the rest being able to enjoy the performance benefits of posted writes.
=> schemas: Allow nonposted-mmio on individual device, children of simple-bus

dtschema/schemas/root-node.yaml
All in One PCs are desktop computers with integrated display. The Linux kernel contains device trees for Apple silicon iMacs (24-inch, M1, 2021) [0] which should use this chassis-type.
The SMBIOS specification [1] specifies "All in One" as `0Dh` in "Table 17 – System Enclosure or Chassis Types" as well.
[0] arch/arm64/boot/dts/apple/t8103-j45[67].dts
[1] https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.8.0.pdf
=> schemas: root-node: Add 'all-in-one' chassis-type

dtschema/schemas/chosen.yaml
Bootloaders typically can be loaded from different storage media, such as eMMC, SD card, SPI flash, EEPROM, but also from non-persistent media such as USB (via proprietary protocols loading directly into SRAM, or fastboot, DFU, etc..), JTAG, ...
This information is usually reported by the SoC-ROM via some proprietary mechanism (some specific address in registers/DRAM for example).
It would be useful to know which medium was used to load the first stage of the bootloader. SoC-ROM shall be ignored and not reported in this property.
This can allow client programs to detect which medium to write to when updating the boot program, or detect if fallback mechanisms to unexpected medium were used to reach the client program's execution.
In cases where a boot program is split into multiple stages …
=> schemas: chosen: add bootsource property
